version: "3.8"
services:
  app:
    build: ./app
    ports:
      - 8080:3000
    volumes:
    - ./app/src:/app/src
    environment:
      TEXTSTORE_HOST: textstore
      WORKER: worker
      TIMEOUT: 10
  worker:
    build: ./worker
    deploy:
      replicas: 1
    ports:
      - 8000:3000
    environment:
      TEXTSTORE_HOST: textstore
    volumes:
      - ./worker/src:/app/src
  textstore:
    image: mongo
    restart: always
    command: --quiet --syslog
    ports:
      - 27017:27017
    volumes:
      - textstore-data:/data/db
      - mongo-config:/data/configdb

volumes:
  textstore-data:
  mongo-config:
