version: "3.8"
services:
  app:
    image: app
    ports:
      - 8080:3000
    environment:
      TEXTSTORE_HOST: textstore
      WORKER: worker
      TIMEOUT: 10

  worker:
    image: worker
    deploy:
      replicas: 5
    environment:
      TEXTSTORE_HOST: textstore
      
  textstore:
    image: mongo
    restart: always
    command: --quiet --syslog
    expose:
      - "27017"
    volumes:
      - textstore-data:/data/db
      - mongo-config:/data/configdb

volumes:
  textstore-data:
  mongo-config:
